### ISSUE TITLE
点击Recall后,小球没有移动,历史坐标在依次清除

### ISSUE THREAD

**Issue by zb737472783** [wcai49/Show_Of_Recall#1]
您好,想问下爱,点击Recall后,小球没有移动,但历史坐标在依次清除

**Comment by zb737472783** [comment]
知道了,其实动了,只是微动,存储的是上一次静态开始的位置,距离上一次动静很小的话,不明显

**Comment by wcai49** [comment]
调整了（看起来）合适的记录频率，如果问题还存在的话麻烦随时再提issues哈，感谢
